### ISSUE TITLE
hprose 处理 emoji 报 iconv异常

### ISSUE THREAD

**Issue by chenjinya** [hprose/hprose-php#39]
异常栈如下
```
Exception: iconv(): Detected an illegal character in input string in /home/work/app/vendor/hprose/hprose/src/Hprose/Client.php:368
Stack trace:
#0 /home/work/app/vendor/hprose/hprose/src/Hprose/Client.php(470): Hprose\Client->decode('Es54"iconv(): D...', Array, Object(stdClass))
#1 /home/work/app/vendor/hprose/hprose/src/Hprose/Client.php(482): Hprose\Client->syncInvokeHandler('updateUserInfo', Array, Object(stdClass))
#2 /home/work/app/vendor/hprose/hprose/src/Hprose/HandlerManager.php(40): Hprose\Client->invokeHandler('updateUserInfo', Array, Object(stdClass))
#3 /home/work/app/vendor/hprose/hprose/src/Hprose/Client.php(598): Hprose\HandlerManager->Hprose\{closure}('updateUserInfo', Array, Object(stdClass))
#4 /home/work/app/vendor/hprose/hprose/src/Hprose/Client.php(423): Hprose\Client->invoke('updateUserInfo', Array)
#5 /home/work/app/api/modules/user/controllers/InfoController.php(205): Hprose\Client->__call('updateUserInfo', Array)
#6 [internal function]: api\modules\user\controllers\InfoController->actionUpdate()
#7 /home/work/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /home/work/app/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#9 /home/work/app/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('update', Array)
#10 /home/work/app/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('user/info/updat...', Array)
#11 /home/work/app/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /home/work/app/api/web/index.php(16): yii\base\Application->run()
#13 {main}
```

**Comment by andot** [comment]
你装 hprose 扩展试试看，hprose 扩展对 utf8 的支持不依赖 iconv。

**Comment by chenjinya** [comment]
@andot 好的，我试试先

**Comment by chenjinya** [comment]
@andot 装了hprose的扩展，使用的phpzie，在/usr/lib64/php/modules/ 也有了hprose.so的扩展， 在php.ini也配置了
```
[hprose]
extendsion=hprose.so
```

重启php后，还是提示一样的问题..是我配置错了吗~？

**Comment by chenjinya** [comment]
没事儿了，我发现不是hprose的问题。
